### ISSUE TITLE
ModuleNotFoundError: No module named 'regex' / ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by lindenb** [rezwanhosseini/MotifDiff#1]
Hi all,

for your information:

I was just giving your tool a try. I created a fresh apptainer container to include your tool using `pip` but when I invoked `getDiff` there was an error:

```
ModuleNotFoundError: No module named 'regex'
```

so may be your `pip install` is missing this module.

**Comment by lindenb** [comment]
(later)
after I added `regex` there were some other errors.

```
# I know it won't work with those non-existing files, I just want test if the tool is able to launch.

Apptainer> getDiff --genome hg19 --motif motif_file --vcf vcf_file --out output_file

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/bin/getDiff", line 5, in <module>
    from MotifDiff.MotifDiff import app
  File "/usr/local/lib/python3.12/dist-packages/MotifDiff/MotifDiff.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib/python3/dist-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/lib/python3/dist-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/lib/python3/dist-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib/python3/dist-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


Traceback (most recent call last):
  File "/usr/local/bin/getDiff", line 5, in <module>
    from MotifDiff.MotifDiff import app
  File "/usr/local/lib/python3.12/dist-packages/MotifDiff/MotifDiff.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib/python3/dist-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/lib/python3/dist-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/lib/python3/dist-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib/python3/dist-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

**Comment by rezwanhosseini** [comment]
thanks for the feedback @lindenb! i added regex to the modules to be installed along with the package. i also fixed the  incompatibility error with numpy version. unfortunately not all modules are compatible with numpy>2 so we'd have to stick with lower versions for now. but it should be installed and run with no errors now after upgrading the package. 
let us know if you run into any other issues!

**Comment by lindenb** [comment]
@rezwanhosseini thanks , I'll try tomorrow morning.

**Comment by lindenb** [comment]
it's fixed but i've got a new bug.
I'll post a new issue.
